Update pull-request-account-compression.yml
Signed-off-by: StormOutlawImmortal #STMX <32193194+melissamforbs@users.noreply.github.com>

diff --git a/.github/workflows/pull-request-account-compression.yml b/.github/workflows/pull-request-account-compression.yml
--- a/.github/workflows/pull-request-account-compression.yml
+++ b/.github/workflows/pull-request-account-compression.yml
@@ -97,4 +97,13 @@ jobs:
             node-
       - name: Set env vars
         run: echo "SOLANA_VERSION=v2.0.14" >> $GITHUB_ENV
-      - run: ./ci/js-test-account-compression.sh
+      - run: ./ci/js-test-account-compression.sh#!/bin/bash
+RETRY_COUNT=5
+for i in $(seq 1 $RETRY_COUNT); do
+    cargo +1.78.0 test-sbf -- --nocapture && break || {
+        echo "Attempt $i failed. Retrying in 10 seconds..."
+        sleep 10
+    }
+done
+
+      
